services:
  mosaic-generator:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - uploads_data:/app/uploads
    restart: unless-stopped

volumes:
  uploads_data: